### ISSUE TITLE
dev-lang/lazarus-2.2.4 missing dependencies "make" and "gdb"

### ISSUE THREAD

**Issue by nomorelogic** [macaroni-os/macaroni-funtoo#11]
When Lazarus starts, a dialog is shown where the requirements for the IDE are listed.
At present "make" and "gdb" are missing, installing them will solve the problem.
You should include "make" and "gdb" in the package dependencies.

**Comment by nomorelogic** [comment]
PS:
package name is: dev-lang/lazarus-2.2.4

**Comment by geaaru** [comment]
Fixed https://github.com/geaaru/geaaru_overlay/commit/46df274deb86af6521e9bdea309c23325c961d34

New ebuidls will be correct.
