### ISSUE TITLE
Thunar, plugins request

### ISSUE THREAD

**Issue by nomorelogic** [macaroni-os/macaroni-funtoo#12]
I would like to request the addition of Thunar plugins.
Reference plugin list:
https://www.funtoo.org/Thunar_Plugins

It would be very useful to have at least "thunar-shares-plugin" and "thunar-vcs-plugin".

**Comment by geaaru** [comment]
Packages added: https://github.com/macaroni-os/macaroni-funtoo/commit/6274fc3a375c2387ce7f5bf8bda01c5e82e5e557

Will be available on the testing repository from tomorrow and on the stable repository with the next release.

Thanks to report this.
