### ISSUE TITLE
macaroni site not working with  iso downloads

### ISSUE THREAD

**Issue by Penguins4** [macaroni-os/macaroni-funtoo#16]
iso mirrors fail when attempting to download any iso from the macaroni os website

**Comment by geaaru** [comment]
It's possible that it has been a temporary down of our GARR mirror. At the moment I haven't issues.
I think you should wait for ISO 23.11 to avoid the upgrading process.
The new ISOs will be available in a few days.
I am leaving this issue open until ISO 23.11 is online.

**Comment by geaaru** [comment]
ISOs 23.11 are available for download. Feel free to reopen this for other issues. Thanks for reporting.
