### ISSUE TITLE
Trying to boot MacaroniOS from iso on a  multiboot usb

### ISSUE THREAD

**Issue by fredmyra** [macaroni-os/macaroni-funtoo#3]
I am very much unsure about posting this here, excuse me if if is not appropriate.

I  have been fighting with this issue or months and haven\t found a pplace on the web that will give me answers.

this the structure of the usb:
```
sdc      8:32   1  57.8G  0 disk 
├─sdc1   8:33   1    33M  0 part # bios boot
├─sdc2   8:34   1   512M  0 part # ESP
├─sdc3   8:35   1     8G  0 part /run/media/anon/artix
└─sdc4   8:36   1  49.2G  0 part /run/media/anon/ISOs
```

This are the relevant parts of the grub.cfg I am trying, based on the isolinux in the iso - the only source of inspiration I was able to find;
```
# Config for GNU GRand Unified Bootloader (GRUB)
# /boot/grub/grub.cfg
# januari 12, 2023
# Timeout for menu
  set timeout=-1
# Default boot entry
  set default=0
# Menu Colours
  set menu_color_normal=white/black
  set menu_color_highlight=white/green
# persistent block device  naming
# define globally (i.e outside any menuentry)
  insmod search_fs_uuid
  insmod gzio
  insmod part_gpt
  insmod part_msdos
  insmod fat
  insmod loopback
  insmod iso9660
  insmod ext2
  insmod all_video
  set gfxpayload=keep
  set root=(hd0,gpt4)
menuentry "MocaccinoOS.iso" {
   linux /loop_mounting/Mocaccino/boot/kernel.xz cdroot rootdelay=7 nomodeset failsafe # vga=ask 
#  linux /loop_mounting/Mocaccino/boot/kernel.xz root=LABEL=ISOs rootdelay =7 nomodeset failsafe # vga=ask 
  initrd (loop)/boot/rootfs.xz
}
menuentry "MocaccinoOS iso expanded" {
  set isofile="/MocaccinoOS-MATE-0.20220903.iso"
  loopback loop (hd0,gpt4)$isofile
  linux (loop)/boot/kernel.xz cdroot rootdelay=7 nomodeset failsafe # vga=ask 
  initrd (loop)/boot/rootfs.xz
}
```

In many attempts varyin parametersin the menu entry I comsistently got the error:
` 
/sbin/init in rootfs not found, dropping to emergency shell`

I enclose a screenshot with that message:
![IMG_20230131_003337_HDR](https://user-images.githubusercontent.com/85910203/215622052-6fe6770b-ad90-45d8-bc40-6cbe8d9918b3.jpg)

**Comment by geaaru** [comment]
@fredmyra at the moment FWIK the Macaroni ISO doesn't support solutions with multiple ISOs in the same key. You need to write the ISO directly in the key and start it directly.
My doubt is that you post a comment about Mocaccino and not Macaroni. If you want to install Mocaccino OS you need to ask to Mocaccino Devs. Here is for Macaroni OS.

**Comment by fredmyra** [comment]
@ gearu  Thank you so much for your answer, it will save me a lot of time. I  already have a functioning usb key with MacaroniOS, The multiboot is just a convenience and a pretext to learn.
And excuse me 1.000.000 times for miixing up your  creations. I really wanted to ask about Macaroni.  As mentionned I am already a Funtoo user and admirer and Sabayon was once my favourite distro.

**Comment by geaaru** [comment]
y/w. Using multi ISO key is in my backlog but with very low priority. The Funtoo guys stay working a lot about this stuff and I will investigate with them in the near future but now I'm working to rewrite `luet` and add new features and this will grow the quality of the OS.
Reading your last comment, it seems that using a USB key with only the Macaroni OS works correctly. For this reason, I close this issue as not supported. 
Thanks for your feedback and for testing/using Macaroni. I hope that Macaroni OS will become your favorite distro too ;)
