### ISSUE TITLE
add module pinctrl_tigerlake in order to enable MSFT* touchpad (Elan Microelectronics Corp. - VendorId 04F3)

### ISSUE THREAD

**Issue by kurtz81** [macaroni-os/macaroni-funtoo#6]
In order to enable this type of touchpad (Elan - MSFTXXXX) is needed to have the module pinctrl_tigerlake (depend on which motherboard the touchpad is mounted on - pinctrl_sunrisepoint or others).
Major detail are here:
[](https://forums.gentoo.org/viewtopic-t-1086512-start-0.html)

The config on kernel to enable is CONFIG_PINCTRL_TIGERLAKE

**Comment by geaaru** [comment]
The new kernels available on Phoenix 23.05 are with the fix. Closing it. Feel free to reopen this if something goes wrong.
