### ISSUE TITLE
Failed to install free pascal compiler (fpc) 

### ISSUE THREAD

**Issue by nomorelogic** [macaroni-os/macaroni-funtoo#8]
I'm trying to install fpc and lazarus.
While fpc is the compiler, lazarus is the IDE (build using fpc), thus I need, 1st of all, to install fpc.
So, this issue is related to the fpc compiler and not lazarus.

There are many ways to install, this is an attempt to install a snapshot of prebuilded fpc compiler.

I executed this test in a VBox machine using Macaroni-Funtoo-Phoenix-Xfce-Devel-23.03.02.iso.
Steps to reproduce fpc installation (here I installed in /usr/local/fpc, but you can choose another path):
1) luet install binutils
2) mkdir -p /usr/local/fpc
3) cd /usr/local/fpc
4) wget -O fpc-3.2.2.x86_64-linux.tar http://sourceforge.net/projects/freepascal/files/Linux/3.2.2/fpc-3.2.2.x86_64-linux.tar
5) tar xvf fpc-3.2.2.x86_64-linux.tar
6) cd fpc-3.2.2.x86_64-linux
7) ./install.sh

During step (7) you will be asked for some questions:
- install prefix: I used /usr/local
- install documentation: Yes (the answer is not related to this issue, installing doc is optional)
- install demos: No (the answer is not related to this issue, installing demos is optional)

At end, errors are due to libgcc

Running on linux
Write permission in /etc.
Writing sample configuration file to /etc/fpc.cfg
Could not find libgcc
Could not find libgcc
Saved old "fpc.cfg" to "fpc.bak"
Writing sample configuration file to /usr/local/lib/fpc/3.2.2/ide/text/fp.cfg
Could not find libgcc
Could not find libgcc
Saved old "fp.cfg" to "fp.bak"
Writing sample configuration file to /usr/local/lib/fpc/3.2.2/ide/text/fp.ini
Could not find libgcc
Could not find libgcc
Saved old "fp.ini" to "fp.bak"
Writing sample configuration file to /etc/fppkg.cfg
Could not find libgcc
Could not find libgcc
Saved old "fppkg.cfg" to "fppkg.bak"
Writing sample configuration file to /etc/fppkg/default
Could not find libgcc
Could not find libgcc
Saved old "default" to "default.bak"

**Comment by geaaru** [comment]
@nomorelogic I think that here there are steps missing on the initial setup.
I executed these steps directly from the ISO shared:
```
$> luet i elt-patches patch autoconf-archive gcc-config diffutils binutils sandbox
$> /usr/bin/gcc-config 1 && locale-gen && source /etc/profile && eselect gcc set 1 && eselect binutils set 1 && macaronictl env-update
$> source /etc/profile
```

Followed by your steps and the result is:

```
Running on linux
Write permission in /etc.
Writing sample configuration file to /etc/fpc.cfg
Writing sample configuration file to /usr/local/lib/fpc/3.2.2/ide/text/fp.cfg
Writing sample configuration file to /usr/local/lib/fpc/3.2.2/ide/text/fp.ini
Writing sample configuration file to /etc/fppkg.cfg
Writing sample configuration file to /etc/fppkg/default

End of installation.

Refer to the documentation for more information.
```

Let me know. I will integrate I hope soon the package from the Funtoo ebuild

**Comment by nomorelogic** [comment]
it works: using commands as you reported and, after, my steps, the fpc compiler is installed correctly
thanks

**Comment by geaaru** [comment]
:+1: Perfect!
